# Generated by Django 4.0.2 on 2024-04-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='price',
        ),
    ]
